### PR TITLE
update docker-compose promise type to 1.2.0

### PR DESCRIPTION
**Pull request by basvandervlies**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @larsewi can review this?

**Comment by basvandervlies** [comment]
I read from the [issue](https://github.com/basvandervlies/scl_modules/issues/11) that there will be a blog post 2th of Dec. So would be nice if its get merged before the blog post is published:
```
Thanks for the useful module! It will be featured in a monthly module monday blog post on Dec. 2.
```

**Review by larsewi — APPROVED** [review]
Thanks @basvandervlies :rocket: It looks like @craigcomstock has been involved here, so I tagged him for a review. LGTM, but did not test the module.

**Review by craigcomstock — CHANGES_REQUESTED** [review]
See https://github.com/basvandervlies/scl_modules/pull/12/files/875c75f1bf79c469924514696db6452aa409151c..380ecbbd6beef6aa92c0ca2b69ba6da66df5d4eb#r1866283155

I think we need a different fix. I do agree that "docker compose" should be the default if it is available so can try a fix locally.

I am not worried about the blog post going out since the module works as-is so long as you do things "normally" and install docker from docker.io repos. Almost certainly "the way" most folks would do it? :shrug: ?

**Comment by basvandervlies** [comment]
IJ

> See https://github.com/basvandervlies/scl_modules/pull/12/files/875c75f1bf79c469924514696db6452aa409151c..380ecbbd6beef6aa92c0ca2b69ba6da66df5d4eb#r1866283155
> 
> I think we need a different fix. I do agree that "docker compose" should be the default if it is available so can try a fix locally.
> 
> I am not worried about the blog post going out since the module works as-is so long as you do things "normally" and install docker from docker.io repos. Almost certainly "the way" most folks would do it? 🤷 ?

I have a new pull request that properly check the `docker conpose` command.  I will update this pull request with the new commit when merged

**Review by craigcomstock — COMMENTED** [review]
Looks good! I checked the "find docker compose" changes you made and that looks good.

Can you squash the commits? Then I think we are ready to go.

Thanks!

**Review by craigcomstock — APPROVED** [review]
Outstanding. @basvandervlies thanks for adding me to the Authors block. ;) "gratitude" :)

**Pull request merged**
