### PR TITLE
ENT-8249: Add module 'prelinking-disabled' to index

### PR DESCRIPTION
**Pull request by larsewi**
Signed-off-by: larsewi <lars.erik.wik@northern.tech>

### CODE REVIEW

**Review by nickanderson — CHANGES_REQUESTED** [review]
No code to review here, so find comments here: https://tracker.mender.io/browse/ENT-8249

**Comment by larsewi** [comment]
Module can be found [here](https://github.com/larsewi/cfengine-prelinking-disabled)

**Review by nickanderson — CHANGES_REQUESTED** [review]
Comments to your commit in your repo https://github.com/larsewi/cfengine-prelinking-disabled/commit/898b41260728796bb436aca7885956c25ec7be89#diff-2dff0e34cc8166b0c6f95dfb503842e771cb83a4da156f461d17c96200542abb

**Comment by larsewi** [comment]
Changed README. @nickanderson I'd love to chat about the namespace stuff during Agent Is In.

**Comment by olehermanse** [comment]
Done here instead: https://github.com/cfengine/build-index/pull/173

**Pull request closed without merging**
