### PR TITLE
Added lynis-compliance-report v0.0.1

### PR DESCRIPTION
**Pull request by nickanderson**
Depends on https://github.com/cfengine/build-index/pull/262

### CODE REVIEW

**Review by craigcomstock — APPROVED** [review]

**Review by vpodzime — COMMENTED** [review]
I'm not sure what to review here.

**Comment by nickanderson** [comment]
@olehermanse I followed up on our post-standup conversation here.

- Module renamed
- Number of checks reduced

Additionally I ...
- Tweaked categories, mapping Lynis Group-Lynis Category to our category
- Tweaked condition severity, mapping Lynis Group to a severity (basics -> low, performance -> medium, security -> high)

I did not alter the Condition Name. I tried to but I got errors trying to import the JSON via the MP ui.

Screenshot_2022-08-17_144327

**Comment by nickanderson** [comment]
@olehermanse are you holding this PR hostage until MP can accept longer Names?

**Comment by nickanderson** [comment]
> I'm not sure what to review here.

The beautiful screenshot :-D

**Review by vpodzime — APPROVED** [review]
The screenshot looks good to me

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
